sudo: false
language: python
python:
    - "3.6"
install: "pip install tox-travis coverage codecov"
env:
    - PYTHONDONTWRITEBYTECODE=1
script:
    - tox
    - coverage run setup.py test
    - coverage report -m
    - codecov

