[tool.poetry]
name = "scim2-filter-parser"
version = "0.3.5"
description = "A customizable parser/transpiler for SCIM2.0 filters"
license = "MIT"
readme = "README.rst"
homepage = "https://github.com/15five/scim2-filter-parser"
repository = "https://github.com/15five/scim2-filter-parser"
keywords = [
    "scim",
    "2.0",
    "filter"
]
classifiers = [
    "Development Status :: 1 - Planning",
    "Environment :: Web Environment",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Topic :: Internet",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
packages = [
    {include = "scim2_filter_parser", from = "src"},
]
authors = [
    "Paul Logston <paul@15five.com>",
]
maintainers = [
    "Paul Logston <paul.logston@gmail.com>",
]

[tool.poetry.dependencies]
sly = "^0.4"

django = { version = ">=2.2.7", optional = true }

[tool.poetry.extras]
django = ["django"]

[tool.poetry.dev-dependencies]
pytest-runner = ""
pytest = ""

[tool.poetry.scripts]
sfp-lexer= 'scim2_filter_parser.lexer:main'
sfp-parser = 'scim2_filter_parser.parser:main'
sfp-transpiler = 'scim2_filter_parser.transpilers.sql:main'
sfp-query = 'scim2_filter_parser.queries.sql:main'

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tox]
isolated_build = true
envlist =
    py36
    py37
    py38
    flake8

[gh-actions]
python =
    3.6: py36
    3.7: py37
    3.8: py38, flake8

[testenv]
setenv =
    PYTHONDONTWRITEBYTECODE=1
basepython =
    py36: python3.6
    py37: python3.7
    py38: python3.8
whitelist_externals = poetry
commands =
    poetry install -v
    poetry run pytest tests/

[testenv:flake8]
basepython =
    python3.8
deps =
    flake8
commands =
    flake8 src

[flake8]
exclude = __pycache__,.eggs/,.tox/
max-line-length = 120
max-complexity = 8
ignore =
    W391  # blank line at end of file
