name: CI/CD

on: [push]

env:
  PYTHONDONTWRITEBYTECODE: 1

jobs:
  tests:
    name: Python ${{ matrix.python-version }}

    runs-on: ubuntu-latest

    strategy:
      max-parallel: 3
      matrix:
        python-version: ["3.6", "3.7", "3.8"]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install coverage codecov tox tox-gh-actions
      - run: tox

  coverage:
    name: Coverage

    runs-on: ubuntu-latest

    container:
      image: python:3.8-alpine

    steps:
      - uses: actions/checkout@v2
      - run: coverage run setup.py test
      - run: coverage report -m
      - uses: "codecov/codecov-action@v1"
        with:
          fail_ci_if_error: true
